version: "3.7"
services:
  be:
    image: toh-be:2.0.0-SNAPSHOT
    build: ./tour-of-heroes-backend
    ports:
      - "8080:8080"
  fe:
    image: toh-fe:2.0.0-SNAPSHOT
    build: ./angular-tour-of-heroes
    ports:
      - "80:80"
    depends_on:
      - be
